apiVersion: apps/v1
kind: Deployment
metadata:
  name: flag-service
  namespace: toggle
  labels: { app: flag-service }
spec:
  replicas: 2
  selector:
    matchLabels: { app: flag-service }
  template:
    metadata:
      labels: { app: flag-service }
    spec:
      containers:
        - name: flag-service
          image: 473556687259.dkr.ecr.us-east-1.amazonaws.com/toggle/flag-service:latest
          ports:
            - containerPort: 8002
          envFrom:
            - configMapRef: { name: flag-config }
            - secretRef: { name: flag-secret }
          resources:
            requests: { cpu: "100m", memory: "128Mi" }
            limits: { cpu: "500m", memory: "256Mi" }
          readinessProbe:
            httpGet: { path: /health, port: 8002 }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /health, port: 8002 }
            initialDelaySeconds: 10
            periodSeconds: 15
